# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

""" Configuration file holding list of predefeined GCC/SDP packages.
"""

VERSION_MATRIX = {
    "aarch64-linux-gcc_12.2.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/gcc/12.2.0:gcc.BUILD",
        "sha256": "7279b1adb50361b21f5266b001980b6febb35fa8d83170901196b9edae3f06d9",
        "strip_prefix": "aarch64-unknown-linux-gnu",
        "url": "https://github.com/eclipse-score/toolchains_gcc_packages/releases/download/v0.0.4/aarch64-unknown-linux-gnu_gcc12.tar.gz",
    },
    "aarch64-linux-autosd10": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/autosd/10.0:autosd.BUILD",
        "extra_c_compile_flags": [
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc/aarch64-redhat-linux/14/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include",
        ],
        "extra_cxx_compile_flags": [
            "-nostdinc++",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14/aarch64-redhat-linux",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14/backward",
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc/aarch64-redhat-linux/14/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include",
        ],
        "extra_link_flags": [
            "-B",
            "external/%{toolchain_pkg}%/usr/bin",
            "-L",
            "external/%{toolchain_pkg}%/lib64",
            "-L",
            "external/%{toolchain_pkg}%/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/gcc/x86_64-redhat-linux/14",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib64",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib",
            "-lm",
            "-ldl",
            "-lrt",
            "-lstdc++",
        ],
        "sha256": "8d70f31588f864e680db05b1e8053fe93655897af646335c48c2ea5bd6578947",
        "strip_prefix": "sysroot",
        "url": "https://github.com/eclipse-score/inc_os_autosd/releases/download/continuous/autosd-toolchain-aarch64.tar.gz",
    },
    "aarch64-qnx-sdp_8.0.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/qnx/aarch64/sdp/8.0.0:sdp.BUILD",
        "sha256": "f2e0cb21c6baddbcb65f6a70610ce498e7685de8ea2e0f1648f01b327f6bac63",
        "strip_prefix": "installation",
        "url": "https://www.qnx.com/download/download/79858/installation.tgz",
        "gcc_version": "12.2.0",
    },
    "aarch64-linux-yocto": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/yocto/5.0.15:yocto.BUILD",
        "extra_compile_flags": [
            "-mcpu=cortex-a57+crc",
            "-mbranch-protection=standard",
        ],
        "extra_hardening_flags": [
            "-O2",
            "-fstack-protector-strong",
            "-D_FORTIFY_SOURCE=2",
            "-Wformat",
            "-Wformat-security",
            "-Werror=format-security",
        ],
        "extra_c_compile_flags": [
            "-nostdinc",
            "-feliminate-unused-debug-types",
            "-isystem",
            "external/%{toolchain_pkg}%/sysroots/cortexa57-poky-linux/usr/include",
        ],
        "extra_cxx_compile_flags": [
            "-nostdinc++",
            "-feliminate-unused-debug-types",
            # FixMe: why the cxx_builtin_include_directories don't work? We have to hardcode the include paths here, which is not ideal.
            "-isystem",
            "external/%{toolchain_pkg}%/sysroots/cortexa57-poky-linux/usr/include/c++/13.4.0",
            "-isystem",
            "external/%{toolchain_pkg}%/sysroots/cortexa57-poky-linux/usr/include/c++/13.4.0/aarch64-poky-linux",
        ],
        "extra_link_flags": [
            "-Wl,-O1",
            "-Wl,--hash-style=gnu",
            "-Wl,--as-needed",
            "-Wl,-z,relro,-z,now",
            "-lm",
            "-ldl",
            "-lrt",
            "-lstdc++",
        ],
        "sha256": "12f07616f80495da78265022e520a77cdb96d9b4916d06a573f28c84e2f02ee8",
        "strip_prefix": "yocto-sdk-5.0.15-qemuarm64",
        "url": "https://github.com/phongt/yocto-sdk/releases/download/yocto-sdk-5.0.15-12/yocto-sdk-5.0.15-qemuarm64.tar.gz",
        "gcc_version": "13.4.0",
    },
    "x86_64-linux-gcc_12.2.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/x86_64/gcc/12.2.0:gcc.BUILD",
        "sha256": "e9b9a7a63a5f8271b76d6e2057906b95c7a244e4931a8e10edeaa241e9f7c11e",
        "strip_prefix": "x86_64-unknown-linux-gnu",
        "url": "https://github.com/eclipse-score/toolchains_gcc_packages/releases/download/v0.0.4/x86_64-unknown-linux-gnu_gcc12.tar.gz",
    },
    "x86_64-linux-autosd10": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/x86_64/autosd/10.0:autosd.BUILD",
        "extra_c_compile_flags": [
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc/x86_64-redhat-linux/14/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include",
        ],
        "extra_cxx_compile_flags": [
            "-nostdinc++",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14/x86_64-redhat-linux",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14/backward",
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc/x86_64-redhat-linux/14/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include",
        ],
        "extra_link_flags": [
            "-B",
            "external/%{toolchain_pkg}%/usr/bin",
            "-L",
            "external/%{toolchain_pkg}%/lib64",
            "-L",
            "external/%{toolchain_pkg}%/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/gcc/x86_64-redhat-linux/14",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib64",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib",
            "-lm",
            "-ldl",
            "-lrt",
            "-lstdc++",
        ],
        "sha256": "525dcca237dfdff3d6c8f3650a0db77a93638141e8c91252544b37447ef9108c",
        "strip_prefix": "sysroot",
        "url": "https://github.com/eclipse-score/inc_os_autosd/releases/download/continuous/autosd-toolchain-x86_64.tar.gz",
    },
    "aarch64-linux-sdk_0.1.0-ebclfsa": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/ebclfsa/0.1.0:ebclfsa.BUILD",
        "extra_c_compile_flags": [
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc-cross/aarch64-linux-gnu/13/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include",
            "-L",
            "external/%{toolchain_pkg}%/lib/aarch64-linux-gnu",
            "-L",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/x86_64-linux-gnu",
            "--no-canonical-prefixes",
        ],
        "extra_cxx_compile_flags": [
            "-nostdinc++",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include/c++/13",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include/c++/13/aarch64-linux-gnu",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include/c++/13/backward",
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc-cross/aarch64-linux-gnu/13/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include",
            "-L",
            "external/%{toolchain_pkg}%/lib/aarch64-linux-gnu",
            "-L",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/x86_64-linux-gnu",
            "--no-canonical-prefixes",
        ],
        "extra_link_flags": [
            "-B",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/bin",
            "-L",
            "external/%{toolchain_pkg}%/lib/aarch64-linux-gnu",
            "-L",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/x86_64-linux-gnu",
            "-lm",
            "-ldl",
            "-lrt",
            "-static-libstdc++",
            "-static-libgcc",
            "-static",
            "--no-canonical-prefixes",
        ],
        "strip_prefix": "fastdev-sdk-ubuntu-ebclfsa-ebcl-qemuarm64",
        "sha256": "f44286c28d831dc40acdac08ef49f38a2e9cbb057bea38c25834964693785287",
        "url": "https://github.com/Elektrobit/eb_corbos_toolkit/releases/download/v2.0.0-beta1/fastdev-sdk-ubuntu-ebclfsa-ebcl-qemuarm64.tar.gz",
    },
    "x86_64-qnx-sdp_8.0.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/qnx/x86_64/sdp/8.0.0:sdp.BUILD",
        "sha256": "f2e0cb21c6baddbcb65f6a70610ce498e7685de8ea2e0f1648f01b327f6bac63",
        "strip_prefix": "installation",
        "url": "https://www.qnx.com/download/download/79858/installation.tgz",
        "gcc_version": "12.2.0",
    },
    "x86_64-linux-yocto": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/x86_64/yocto/5.0.15:yocto.BUILD",
        "extra_compile_flags": [
            "-m64",
            "-march=core2",
            "-mtune=core2",
            "-msse3",
            "-mfpmath=sse",
        ],
        "extra_hardening_flags": [
            "-O2",
            "-fstack-protector-strong",
            "-D_FORTIFY_SOURCE=2",
            "-Wformat",
            "-Wformat-security",
            "-Werror=format-security",
        ],
        "extra_c_compile_flags": [
            "-nostdinc",
            "-feliminate-unused-debug-types",
            "-isystem",
            "external/%{toolchain_pkg}%/sysroots/core2-64-poky-linux/usr/include",
        ],
        "extra_cxx_compile_flags": [
            "-nostdinc++",
            "-feliminate-unused-debug-types",
            # FixMe: why the cxx_builtin_include_directories don't work? We have to hardcode the include paths here, which is not ideal.
            "-isystem",
            "external/%{toolchain_pkg}%/sysroots/core2-64-poky-linux/usr/include/c++/13.4.0",
            "-isystem",
            "external/%{toolchain_pkg}%/sysroots/core2-64-poky-linux/usr/include/c++/13.4.0/x86_64-poky-linux",
        ],
        "extra_link_flags": [
            "-Wl,-O1",
            "-Wl,--hash-style=gnu",
            "-Wl,--as-needed",
            "-Wl,-z,relro,-z,now",
            "-lm",
            "-ldl",
            "-lrt",
            "-lstdc++",
        ],
        "sha256": "f8663e044bb2a75c6c97dc879981c79bf0ae775a5342f69363dc47a5fba15b33",
        "strip_prefix": "yocto-sdk-5.0.15-qemux86-64",
        "url": "https://github.com/phongt/yocto-sdk/releases/download/yocto-sdk-5.0.15-10/yocto-sdk-5.0.15-qemux86-64.tar.gz",
        "gcc_version": "13.4.0",
    },
}
